import { AiProviderModel, ProviderType, WebSearchMode } from '../types/ai-provider.types';

export const DEFAULT_AI_PROVIDERS: AiProviderModel[] = [
  {
    id: 'openai_default',
    name: 'OpenAI',
    type: ProviderType.OpenAI,
    apiKey: '',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    defaultDialogueModel: 'gpt-4o',
    defaultNamingModel: 'gpt-3.5-turbo',
    isEnabled: true,
    enabledModels: ['gpt-4o', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    isSystem: true,
    sortOrder: 0,
    webSearchMode: WebSearchMode.Tool,
  },
  {
    id: 'anthropic_default',
    name: 'Anthropic Claude',
    type: ProviderType.Anthropic,
    apiKey: '',
    baseUrl: 'https://api.anthropic.com/v1',
    models: ['claude-3-7-sonnet-20250219', 'claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-3-haiku-20240307'],
    defaultDialogueModel: 'claude-3-7-sonnet-20250219',
    defaultNamingModel: 'claude-3-haiku-20240307',
    isEnabled: true,
    enabledModels: ['claude-3-7-sonnet-20250219', 'claude-3-5-sonnet-20241022', 'claude-3-haiku-20240307'],
    isSystem: true,
    sortOrder: 1,
    webSearchMode: WebSearchMode.Tool,
  },
  {
    id: 'gemini_default',
    name: 'Google Gemini',
    type: ProviderType.Gemini,
    apiKey: '',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    defaultDialogueModel: 'gemini-2.5-pro',
    defaultNamingModel: 'gemini-2.5-flash',
    isEnabled: true,
    enabledModels: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    isSystem: true,
    sortOrder: 2,
    webSearchMode: WebSearchMode.Native,
  },
  {
    id: 'deepseek_default',
    name: 'DeepSeek',
    type: ProviderType.DeepSeek,
    apiKey: '',
    baseUrl: 'https://api.deepseek.com/v1',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultDialogueModel: 'deepseek-chat',
    defaultNamingModel: 'deepseek-chat',
    isEnabled: true,
    enabledModels: ['deepseek-chat', 'deepseek-reasoner'],
    isSystem: true,
    sortOrder: 3,
    webSearchMode: WebSearchMode.Tool,
  },
  {
    id: 'kimi_default',
    name: 'Kimi (Moonshot)',
    type: ProviderType.Kimi,
    apiKey: '',
    baseUrl: 'https://api.moonshot.cn/v1',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    defaultDialogueModel: 'moonshot-v1-8k',
    defaultNamingModel: 'moonshot-v1-8k',
    isEnabled: true,
    enabledModels: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    isSystem: true,
    sortOrder: 4,
    webSearchMode: WebSearchMode.Tool,
  }
];
